apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcp-inspector-ingress
spec:
  rules:
    - host: mcp.inspector.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mcp-inspector-http
                port:
                  number: 6274
    - host: mcp-proxy.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mcp-inspector-http
                port:
                  number: 6277