apiVersion: v1
kind: Service
metadata:
  name: mcp-inspector-http
spec:
  type: {{ .Values.service.type }}
  selector:
    app: mcp-inspector
  ports:
    - name: ui
      protocol: TCP
      port: {{ .Values.service.ui.port }}
      targetPort: {{ .Values.service.ui.port }}
    - name: proxy
      protocol: TCP
      port: {{ .Values.service.proxy.port }}
      targetPort: {{ .Values.service.proxy.port }}
