apiVersion: v1
kind: Service
metadata:
  name: mcp-inspector-http
spec:
  type: NodePort
  selector:
    app: mcp-inspector
  ports:
    - name: ui
      protocol: TCP
      port: {{ .Values.SERVICE.UI.PORT }}
      targetPort: {{ .Values.SERVICE.UI.PORT }}
      nodePort: 30274
    - name: proxy
      protocol: TCP
      port: {{ .Values.SERVICE.PROXY.PORT }}
      targetPort: {{ .Values.SERVICE.PROXY.PORT }}
      nodePort: 30277