apiVersion: v1
kind: Service
metadata:
  name: mcp-inspector-http
spec:
  type: NodePort
  selector:
    app: mcp-inspector
  ports:
    - name: ui
      protocol: TCP
      port: 6274
      targetPort: 6274
      nodePort: 30274
    - name: proxy
      protocol: TCP
      port: 6277
      targetPort: 6277
      nodePort: 30277