apiVersion: v1
kind: Service
metadata:
  labels:
    app: mcp-server-service
  name: mcp-server-service
spec:
  ports:
    - port: {{ .Values.SERVICE.PORT }}
      protocol: TCP
      targetPort: {{ .Values.SERVICE.PORT }}
  selector:
    app: mcp-server-service
  type: {{ .Values.SERVICE.TYPE }}
status:
  loadBalancer: {}