apiVersion: v1
kind: Service
metadata:
  labels:
    app: mcp-server-http
  name: mcp-server-http
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    app: mcp-server-http
  type: {{ .Values.service.type }}
