mcp-server:
  replicaCount: 1
  image:
    repository: mcp-server-http
    tag: 1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8091
  ingress:
    host: mcp.server.local

inspector:
  replicaCount: 1
  service:
    type: ClusterIP
    ui:
      port: 6274
    proxy:
      port: 6277
  ingress:
    uiHost: mcp.inspector.local
    proxyHost: mcp-proxy.local
